version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: "development"
      BASE_URL: "http://127.0.0.1:5000"
      FRONTEND_BASE_URL: "http://127.0.0.1:5000"
      EMAIL_QUEUE_NAME: "email_queue"
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      RABBITMQ_URL: ${{ secrets.RABBITMQ_URL }}
      MAILTRAP_API_KEY: ${{ secrets.MAILTRAP_API_KEY }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
    depends_on:
      - rabbitmq
      - db

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      FLASK_ENV: "development"
      BASE_URL: "http://127.0.0.1:5000"
      FRONTEND_BASE_URL: "http://127.0.0.1:5000"
      EMAIL_QUEUE_NAME: "email_queue"
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      RABBITMQ_URL: ${{ secrets.RABBITMQ_URL }}
      MAILTRAP_API_KEY: ${{ secrets.MAILTRAP_API_KEY }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
    depends_on:
      - rabbitmq
      - db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
