image:
  repository: your-dockerhub-username/user-service
  tag: latest

replicaCount:
  api: 1
  worker: 1

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  hostname: api.<your-domain>.site
  certificateArn: arn:aws:acm:us-east-1:xxxxxxxxxxxx:certificate/xxxxxxxxxxxx

worker:
  command: ["python", "email_worker.py"]
