apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | quote }}
  JWT_SECRET_KEY: {{ .Values.secrets.JWT_SECRET_KEY | quote }}
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  RABBITMQ_URL: {{ .Values.secrets.RABBITMQ_URL | quote }}
  MAILTRAP_API_KEY: {{ .Values.secrets.MAILTRAP_API_KEY | quote }}
  SENTRY_DSN: {{ .Values.secrets.SENTRY_DSN | quote }}
  NEW_RELIC_LICENSE_KEY: {{ .Values.secrets.NEW_RELIC_LICENSE_KEY | quote }}
