apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5000
      nodePort: {{ .Values.service.nodePort }}