apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-worker
  template:
    metadata:
      labels:
        app: email-worker
    spec:
      containers:
        - name: email-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["python", "email_worker.py"]
          envFrom:
            - configMapRef:
                name: user-service-config
            - secretRef:
                name: user-service-secrets
